name: Emojipedia
description: Emojipedia App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floating_search_bar: ^0.2.0
  sqflite: ^1.1.7+2
  path: ^1.6.4

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true

  assets:
    - assets/emojipedia-dataset.sqlite

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/launcher-icon.png
